name: CI/CD

on:
  push:
    branches:
      - main

permissions: 
  contents: read 
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: |
          docker build -t ghcr.io/murderose/chmurowe/backend:latest ./backend
          docker build -t ghcr.io/murderose/chmurowe/frontend:latest ./frontend

      - name: Push images
        run: |
          docker push ghcr.io/murderose/chmurowe/backend:latest
          docker push ghcr.io/murderose/chmurowe/frontend:latest

      - name: Basic validation
        run: |
          test -f k8s/namespace.yaml
          test -f k8s/ingress.yaml
          test -f k8s/configmap.yaml

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view
          kubectl get nodes

      - name: Debug kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          cat ~/.kube/config
          kubectl config view

      - name: Deploy
        run: |
          kubectl apply -f k8s/

          kubectl rollout restart deployment/backend -n myapp
          kubectl rollout restart deployment/frontend -n myapp

          kubectl rollout status deployment/backend -n myapp
          kubectl rollout status deployment/frontend -n myapp